[#35] 현재 보이는 유저 카드 셀에서의 타임이 0이 되면 자동으로 다음 셀로 스크롤 구현
THT-Team/THT-iOS pull request #38
Opened 2023-10-07 08:11 UTC by Minny27

## Motivation ⍰

- 현재 보이는 유저 카드 셀에서의 타임이 0이 되면 자동으로 다음 셀로 스크롤 구현하기 위함

<br>

## Key Changes 🔑

미리보기는 다음과 같습니다.

<img src="https://github.com/THT-Team/THT-iOS/assets/68800789/3be01177-4241-409d-bb3a-9939a2faf3cf" width=25%>

현재 보이는 유저 카드 셀에서의 타임이 0이되면 자동으로 다음 셀로 스크롤되고 그 셀의 타이머가 시작됩니다.
유저 카드 컬렉션 뷰의 각 셀에 대해 대한 뷰모델을 만들고 그 뷰모델에서 구독을 생성합니다.
이 때, 구독을 하는 순간부터 타이머가 돌기 때문에 현재 보이는 유저 카드 셀의 타임이 0이 됐을 때 알림을 보내기 위해
샐을 생성할 때 time이 0이 됐을 때의 동작을 delegate에 위임합니다.
그래서 isTimeOver driver의 파라미터가 true가 되면 delegate로 scrollToNext함수를 호출합니다.
delegate를 준수하는 vc에서 scrollToNext를 호출하면 timeOverTrigger event에서 void를 emit하도록 해서
timeOverTrigger가 emit할 때만 해당 셀에 대한 구독을 생성합니다.(bindViewModel)
다음 셀로 넘어가기 위해서 현재의 인덱스를 저장하는 BehaviorSubject 상수를 구독해서 index를 갱신받아서
vc에서 do(onNext:)로 특정 셀의 index 스크롤되도록 구현했습니다.

1. 더 쉽게 구현할 수 있는 방법이 있을 지 궁금합니다.
- viewModel에서 input, output, tranform의 형태를 유지하려다보니 저도 vm에서 구독하게 되는 상황이 나오게 되더군요..

2. 네트워크 에러나 다른 탭으로 넘어갔을 떄 시간을 멈춰야할 거 같은데 Driver는 complete를 하지 않다보니
중지 및 재개를 어떻게 구현할지 좀 고민됩니다.

<br>

## To Reviewers 🙏🏻

- [ ] 현재 보이는 유저 카드 셀의 타이머가 0초가 됐을 때, 다음 셀로 자동으로 넘어가는지 확인해주세요
- [ ] 메모리 누수나 구독이 중복이 생기지 않을 지도 한 번 봐주세요

<br>

## Linked Issue 🔗

- [ ] #35

2023-10-08 03:20 UTC, ibcylon requested changes
고생하셨습니다. 
RxDataSources 사용시 Preview가 안되더라구요. 
DiffableDataSource로 변경하였더니 됩니다. 

Diffable로 변경한 코드도 첨부할테니 반영해보시는 것도 좋을 것 같습니다.

2023-10-08 03:20 UTC, ibcylon commented on Falling/Sources/Feature/Main/MainViewController.swift
> +#if DEBUG
Preview 부분 디버그로 이동
RxDataSource 사용 시 Preview 사용 안 됨

2023-10-08 03:20 UTC, ibcylon commented on Falling/Sources/Feature/Main/MainViewModel.swift
> +    let currentPage = timeOverTrigger.withLatestFrom(currentIndex.asDriver(onErrorJustReturn: 0)) { _, page in
timeOverTrigger랑 합성 시 맨 처음 실행이 안되어서 수정 startWith(0) 추가함

2023-10-08 03:20 UTC, ibcylon approved these changes

2023-10-08 13:54 UTC, Minny27 commented
확인해주셔서 감사하고 머지하겠습니다!

2023-10-08 13:55 UTC, merged

2024-02-15 03:09 UTC, Minny27 commented on Falling/Sources/Feature/Main/MainViewModel.swift
> +    let currentPage = timeOverTrigger.withLatestFrom(currentIndex.asDriver(onErrorJustReturn: 0)) { _, page in
0번 째 셀일 때의 처리를 고민했었는데, 두 시퀀스를 withLatestFrom으로 합성해서 startWith으로 처음 값을 추가할 수 있다는 것을 알았네요bb

2024-02-15 03:09 UTC, Minny27 commented on Falling/Sources/Feature/Main/MainViewController.swift
> +#if DEBUG
이 부분도 확인했습니다!